services:
  ops-lab:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ops-lab

    stdin_open: true
    tty: true

    restart: unless-stopped

    env_file:
      - ./docker/.env

    environment:
      - TZ=Asia/Tokyo

    working_dir: /home/r.h

    volumes:
     # スクリプトだけ
     - ./docker:/home/r.h/docker:ro

     # バックアップ保存
     - ./backup:/home/r.h/backup

     # ログ分離
     - ./logs/monitor:/var/log/ops-lab/monitor
     - ./logs/backup:/var/log/ops-lab/backup
     - ./logs/cron:/var/log/ops-lab/cron

    healthcheck:
      test: ["CMD-SHELL", "pgrep cron"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
