#!/bin/bash

ops_help(){
  echo "ops-lab CLI"
  echo "back                : コンテナに入る"
  echo "up                  : 起動"
  echo "down                : 停止"
  echo "restart             : 再起動"
  echo "rebuild             : 再構築"
  echo "update              : git pull + restart"
  echo "logs [service]      : ログ"
  echo "status              : 状態一覧"
  echo "health              : ヘルスチェック"
  echo "cron                : cron設定表示"
  echo "exec [cmd]          : 実行"
  echo "cat [path]          : ファイル閲覧"
  echo "backup              : バックアップ実行"
  echo "prune               : Docker不要データ削除"
  echo "stats               : 全体stats"
  echo "errors              : error抽出"
  echo "fix                 : 自動復旧"
  echo "diagnose            : 総合診断"
  echo "info                : サマリー"
  echo "check-all           : 総合ヘルスチェック"
  echo "disk                : ディスク監視"
  echo "clean               : pruneを実行"
  echo "top                 : コンテナ使用状況"
  echo "git                 : git status"
  echo "pull                : git pull"
  echo "config              : docker compose設定表示"
  echo "version             : CLIバージョン表示"
}
